version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    branchs:
      only:
        - master
        - devel
        - unstable

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python3 manage.py check_general
      - run:
          command: |
            . venv/bin/activate
            python3 manage.py check_stylesheet
      - run:
          command: |
            . venv/bin/activate
            python3 manage.py check_complexity
      - run:
          command: |
            . venv/bin/activate
            python3 manage.py make_db
            python3 manage.py test_report
      - store_artifacts:
          path: test-reports/
          destination: tr1
