version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    branchs:
      only:
        - master
        - devel

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd DreamRich
            pylint --load-plugins pylint_django dreamrich --rcfile=../.pylintrc
      - run:
          command: |
            . venv/bin/activate
            radon cc ../DreamRich
      - run:
          command: |
            . venv/bin/activate
            cd DreamRich
            coverage run manage.py test
            coverage report
      - store_artifacts:
          path: test-reports/
          destination: tr1
